apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: actions=shinobislayer/actions
    argocd-image-updater.argoproj.io/actions.update-strategy: latest
    argocd-image-updater.argoproj.io/actions.allow-tags: regexp:^2025\.\d+\.\d+-.*$
    argocd-image-updater.argoproj.io/actions.pull-secret: secret:argocd/dockerhub-secret
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: https://github.com/ShinobiSlayer/actions.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
